### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jackcarlisle** [numo-labs/taggable-ui#14]
ViewPane
* [x] vertical scroll bar 
* [x] onChange text input 
* [x] + button adds to array
* [x] save button

**Comment by jackcarlisle** [comment]
Hook up buttons

* [ ] save new config
* [ ] delete existing value
* [ ] add new value
* [ ] save in modals

**Comment by nikhilaravi** [comment]
closing this as all the tasks seem to have been completed!
